language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "nightly"
install:
  - python setup.py develop
  - pip install webob webtest coverage
script: python -bb $(which nosetests)
